// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  workspaceStatus: () =>
    typedError<WorkspaceStatusResponse, IpcError>(
      __TAURI_INVOKE("workspace_status"),
    ),
  saveProject: (request: SaveProjectRequest) =>
    typedError<SaveProjectResponse, IpcError>(
      __TAURI_INVOKE("save_project", {
        request: {
          ...request,
          graph: { ...request.graph, nodes: request.graph.nodes.map((i) => i) },
        },
      }),
    ),
  loadProject: (filePath: string) =>
    typedError<LoadProjectResponse, IpcError>(
      __TAURI_INVOKE("load_project", { filePath }),
    ).then(
      (v) =>
        (v.status === "ok"
          ? {
              ...v,
              data: {
                ...v.data,
                graph: {
                  ...v.data.graph,
                  nodes: v.data.graph.nodes.map((i) => i),
                },
              },
            }
          : v) as typeof v,
    ),
  extractFrame: (request: ExtractFrameRequest) =>
    typedError<ExtractFrameResponse, IpcError>(
      __TAURI_INVOKE("extract_frame", { request }),
    ),
  getPromptContext: (request: PromptContextRequest) =>
    typedError<ComposedPromptResponse, IpcError>(
      __TAURI_INVOKE("get_prompt_context", { request }),
    ),
  setStyleLock: (projectId: string, styleLockText: string | null) =>
    typedError<StyleLockResponse, IpcError>(
      __TAURI_INVOKE("set_style_lock", { projectId, styleLockText }),
    ),
  concatSegments: (request: ConcatSegmentsRequest) =>
    typedError<ExportVideoResponse, IpcError>(
      __TAURI_INVOKE("concat_segments", { request }),
    ),
  previewExport: (projectId: string, segmentPaths: string[]) =>
    typedError<PreviewExportResponse, IpcError>(
      __TAURI_INVOKE("preview_export", { projectId, segmentPaths }),
    ),
  exportVideo: (request: ExportVideoRequest) =>
    typedError<ExportVideoResponse, IpcError>(
      __TAURI_INVOKE("export_video", { request }),
    ),
  exportSegment: (request: ExportSegmentRequest) =>
    typedError<ExportSegmentResponse, IpcError>(
      __TAURI_INVOKE("export_segment", { request }),
    ),
  setupVault: (request: SetupVaultRequest) =>
    typedError<SetupVaultResponse, IpcError>(
      __TAURI_INVOKE("setup_vault", { request }),
    ),
  unlockVault: (request: UnlockVaultRequest) =>
    typedError<UnlockVaultResponse, IpcError>(
      __TAURI_INVOKE("unlock_vault", { request }),
    ),
  lockVault: () =>
    typedError<LockVaultResponse, IpcError>(__TAURI_INVOKE("lock_vault")),
  checkVaultStatus: () =>
    typedError<VaultStatusResponse, IpcError>(
      __TAURI_INVOKE("check_vault_status"),
    ),
  resetVault: (request: ResetVaultRequest) =>
    typedError<ResetVaultResponse, IpcError>(
      __TAURI_INVOKE("reset_vault", { request }),
    ),
};

/* Types */
export type ComposedPromptResponse = {
  finalComposedPrompt: string;
  styleLockApplied: string | null;
  contextCarryOverApplied: string | null;
  totalCharacters: number;
  isTruncated: boolean;
};

export type ConcatSegmentsRequest = {
  clientRequestId: string;
  projectId: string;
  segmentPaths: string[];
  outputPath: string;
  format: OutputFormat;
  resolution: ResolutionPreset;
};

export type ErrorDomain =
  | "STORAGE"
  | "PROJECT"
  | "CONTINUITY"
  | "EXPORT"
  | "VAULT";

export type ExportSegmentRequest = {
  segmentId: string;
  sourceVideoPath: string;
  targetPath: string;
  format: OutputFormat;
  resolution: ResolutionPreset;
};

export type ExportSegmentResponse = {
  exportedPath: string;
  fileSizeBytes: number;
};

export type ExportVideoRequest = {
  clientRequestId: string;
  projectId: string;
  format: OutputFormat;
  resolution: ResolutionPreset;
  videoBitrateKbps: number | null;
  audioBitrateKbps: number | null;
  outputDirectory: string;
  customFilename: string | null;
};

export type ExportVideoResponse = {
  success: boolean;
  outputPath: string;
  durationSeconds: number | null;
  fileSizeBytes: number;
};

export type ExtractFrameRequest = {
  videoPath: string;
  outputDirectory: string;
  method: string;
};

export type ExtractFrameResponse = {
  framePath: string;
  resolution: FrameResolution;
  extractionDurationMs: number;
};

export type FrameResolution = {
  width: number;
  height: number;
};

export type IpcError = {
  code: string;
  message: string;
  domain: ErrorDomain;
  details: { [key in string]: string };
  timestamp: number | null;
  retryable: boolean;
};

export type LoadProjectResponse = {
  projectName: string;
  version: string;
  settings: ProjectSettings;
  graph: ProjectGraphData;
  assets: string[];
  updatedAt: string;
};

export type LockVaultResponse = {
  status: string;
  lockedAt: number;
};

export type NodePosition = {
  x: number | null;
  y: number | null;
};

export type OutputFormat = "mp4" | "webm";

export type PreviewExportResponse = {
  previewFilePath: string;
  segmentMarkers: (number | null)[];
  totalDurationSeconds: number | null;
};

export type ProjectEdge = {
  id: string;
  source: string;
  target: string;
  sourceHandle: string | null;
  targetHandle: string | null;
};

export type ProjectGraphData = {
  nodes: ProjectNode[];
  edges: ProjectEdge[];
  viewport: ViewportData;
};

export type ProjectNode = {
  id: string;
  type: string;
  position: NodePosition;
  data: any;
};

export type ProjectSettings = {
  defaultModel: string;
  autoSaveIntervalSeconds: number;
  styleLockText: string | null;
};

export type PromptContextRequest = {
  currentPrompt: string;
  previousPrompts: string[];
  styleLockText: string | null;
};

export type ProviderMode = "manual_handoff" | "official_api";

export type ResetVaultRequest = {
  confirmationFlag: string;
};

export type ResetVaultResponse = {
  success: boolean;
  wipedAt: number;
};

export type ResolutionPreset = "original" | "1080p" | "720p";

export type SaveProjectRequest = {
  filePath: string;
  projectName: string;
  settings: ProjectSettings;
  graph: ProjectGraphData;
};

export type SaveProjectResponse = {
  savedPath: string;
  savedAt: string;
  fileSizeBytes: number;
};

export type SetupVaultRequest = {
  clientRequestId: string;
  masterPassword: string;
  confirmPassword: string;
  autoLockTimeoutMinutes: number | null;
};

export type SetupVaultResponse = {
  status: string;
  vaultCreatedAt: number;
  autoLockTimeoutMinutes: number;
};

export type StyleLockResponse = {
  projectId: string;
  styleLockText: string | null;
  updatedAt: number;
};

export type UnlockVaultRequest = {
  masterPassword: string;
};

export type UnlockVaultResponse = {
  status: string;
  unlockedAt: number;
  activeAccountCount: number;
};

export type VaultState = "uninitialized" | "locked" | "unlocked";

export type VaultStatusResponse = {
  state: VaultState;
  autoLockTimeoutMinutes: number;
  hasActiveLockout: boolean;
  lockoutRemainingSeconds: number | null;
  lastUnlockedAt: number | null;
};

export type ViewportData = {
  x: number | null;
  y: number | null;
  zoom: number | null;
};

export type WorkspaceStatusResponse = {
  databasePath: string;
  migrationCount: number;
  providerMode: ProviderMode;
};

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (error) {
    if (error instanceof Error) {
      throw error;
    }
    return { status: "error", error: error as unknown as E };
  }
}

const _assertTypedErrorFollowsContract: <T, E>(
  result: Promise<T>,
) => Promise<any> = typedError;
