// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  workspaceStatus: () =>
    typedError<WorkspaceStatusResponse, IpcError>(
      __TAURI_INVOKE("workspace_status"),
    ),
};

/* Types */
export type ErrorDomain = "STORAGE";

export type IpcError = {
  code: string;
  message: string;
  domain: ErrorDomain;
  details: { [key in string]: string };
  timestamp: number | null;
  retryable: boolean;
};

export type ProviderMode = "manual_handoff" | "official_api";

export type WorkspaceStatusResponse = {
  databasePath: string;
  migrationCount: number;
  providerMode: ProviderMode;
};

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (error) {
    if (error instanceof Error) {
      throw error;
    }
    return { status: "error", error: error as unknown as E };
  }
}

const _assertTypedErrorFollowsContract: <T, E>(
  result: Promise<T>,
) => Promise<any> = typedError;
